### ISSUE TITLE
TypeError: Cannot set property navigator of #<Object> which has only a getter

### ISSUE THREAD

**Issue by matgayno** [webex/webex-js-sdk#3393]
**Describe the bug**
Importing the SDK into NodeJS results in the following issue:
```
node_modules/@webex/internal-media-core/dist/cjs/index.js:288
        commonjsGlobal.navigator = {
                                 ^

TypeError: Cannot set property navigator of #<Object> which has only a getter
    at /node_modules/@webex/internal-media-core/dist/cjs/index.js:288:34
    at /node_modules/@webex/internal-media-core/dist/cjs/index.js:313:7
    at /node_modules/@webex/internal-media-core/dist/cjs/index.js:1395:5
    at Object.<anonymous> (/node_modules/@webex/internal-media-core/dist/cjs/index.js:1396:3)
    at Module._compile (node:internal/modules/cjs/loader:1378:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1437:10)
    at Module.load (node:internal/modules/cjs/loader:1212:32)
    at Module._load (node:internal/modules/cjs/loader:1028:12)
    at Module.require (node:internal/modules/cjs/loader:1237:19)
    at require (node:internal/modules/helpers:176:18)

Node.js v21.6.1
```

Tested both using import statement and require statement in commonjs and module types.

**To Reproduce**
Create a blank project on MacOS 14.3 M2 Pro Node 21.6.1
Install Webex SDK and import SDK into a file
Execute the file

**Platform (please complete the following information):**
 - OS: MacOS 14.3
 - Node 21.6.1
 - Device Type Macbook Pro M2 Pro

**Comment by matgayno** [comment]
Moving 18.18.0 sorted it, thanks
