### ISSUE TITLE
Webex SDK 3.0.0 not compatible with any version of NodeJS

### ISSUE THREAD

**Issue by Tiuipuv** [webex/webex-js-sdk#3510]
**Describe the bug**
The following script fails to initialize in NodeJS:
```js
import webex from 'webex';

webex.init({credentials: '<valid credentials were provided here>'});
```

Yielding the following error:
```
ReferenceError: window is not defined
    at Object.<anonymous> ([...]\node_modules\@webex\plugin-meetings\node_modules\@webex\internal-media-core\dist\cjs\index.js:2065:29024)
    at Module._compile (node:internal/modules/cjs/loader:1364:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)
    at Module.load (node:internal/modules/cjs/loader:1203:32)
    at Module._load (node:internal/modules/cjs/loader:1019:12)
    at Module.require (node:internal/modules/cjs/loader:1231:19)
    at require (node:internal/modules/helpers:177:18)
    at Object.<anonymous> ([...]\node_modules\@webex\plugin-meetings\dist\meetings\index.js:35:26)
    at Module._compile (node:internal/modules/cjs/loader:1364:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)
```

This has been tested with nodejs `v12`, `v14`, `v16`, `v18`, and `v20`.
package.json:
```json
{
  "name": "test_webex",
  "type": "module",
  [...]
  "dependencies": {
    "webex": "^3.0.0"
  }
}
```
This error is produced for both ESM modules and CommonJS scripts.

**To Reproduce**
1. create a blank npm project using `npm init`
2. install webex sdk with `npm install webex`
3. create `index.js`, with the above code (enter valid bot id)
4. run with `node index.js`
5. See error

**Expected behavior**
Webex SDK successfully imports into script.

**Platform (please complete the following information):**
 - OS: Windows 10 Pro 22H2
 - Browser: N/A (NodeJS)
 - Version: v12.22.12, v14.21.3, v16.20.2, v18.20.0, v20.12.0
 - Device Type: Desktop

**Comment by valgaze** [comment]
+1 was about to file an issue as well

Confirm failure in node 21

<img width="934" alt="image" src="https://github.com/webex/webex-js-sdk/assets/1396559/901e1f5f-a691-4c17-bbd6-ba00909e96d6">

**Comment by valgaze** [comment]
@Tiuipuv 

Two things:

1. This is happening because code modifies `globalThis.navigator` which in node 21, the `navigator` object is special

- https://github.com/nodejs/node/issues/50269
- 
2. Regardless the WebEx sdk is **NOT** supporting (yet?) newer versions of node: [Feb 2024]  https://github.com/webex/webex-js-sdk/issues/3393#issuecomment-1959182736

Regarding item 1:

- In the dist code (@webex/internal-media-core/dist/cjs/index.js) there's this bummer ternary:

```
var commonjsGlobal = typeof globalThis !== 'undefined' ? globalThis : typeof window !== 'undefined' ? window : typeof global !== 'undefined' ? global : typeof self !== 'undefined' ? self : {};
```
When unpacked it looks liek this (and 1st condition matches in node21): 

```
let commonjsGlobal;

if (typeof globalThis !== 'undefined') {
  commonjsGlobal = globalThis;
} else if (typeof window !== 'undefined') {
  commonjsGlobal = window;
} else if (typeof global !== 'undefined') {
  commonjsGlobal = global;
} else if (typeof self !== 'undefined') {
  commonjsGlobal = self;
} else {
  commonjsGlobal = {};
}
```

Regarding item 2: The lack of updates is a bummer, however, there might be fixes coming from node patches itself. The now-term solution is back down a version

**Comment by Tiuipuv** [comment]
@valgaze 

Thank you for your in depth analysis. However, I am not sure downgrading to any version of node works. I noticed this navigator error on v20+, but all versions below 20 all the way down to 12 we're also failing to startup as well (tested using volta).

When you proposed the 'now-term' solution of downgrading, were you referring to downgrading node, or the package itself back to `2.60.2`?

**Comment by valgaze** [comment]
@Tiuipuv I'm realizing your error is slightly different:

Your issue: issues about window object in many versions of node as you stated

Other issue: globalThis.navigator only occurs in node 21+

They seem related but curious what the maintainers of this library think, but maybe it's smart to split this into separate issues

**Comment by sreenara** [comment]
@Tiuipuv thanks for reporting this issue. We have also observed this internally and are currently looking into this. Will provide updates once we have a chance to identify where the root cause is.

Just another note that at this time, we haven't tested all the features of the JS SDK with Node 18 and above. Our applications are running Node 16 and consuming the SDK.

**Comment by sreenara** [comment]
Tagging @ricardocasares as well from #2242

**Comment by sreenara** [comment]
Hey folks, I did some testing and here's a workaround you'll can use to continue testing. I tested this locally and was able to run it on Node 16, 18 and 20 to establish a successful registration with `webex.meetings`

```
global.window = {};
global.window.location = {};
global.window.navigator = {
    userAgent: 'test'
};
global.window.setTimeout = setTimeout;
// global.Webex = {};

const Webex = require('webex');

const webex = (window.webex = Webex.init({
    credentials: {
      access_token: 'token'
    }
  }));

webex.once('ready', () => {
    if (webex.canAuthorize) {
        console.log('webex is authorized');
        webex.meetings.register().then(() => {console.log('registered to meetings', webex.internal.device.userId);})
    }
});
```

**Comment by arun3528** [comment]
@sreenara  there is a need to discuss about how to ship non browser package efficiently + testing

**Comment by csprocket777** [comment]
When doing an ESM import, the issue remains, even with the suggested fix:
```typescript
global.window = {};
global.window.location = {};
global.window.navigator = {
    userAgent: "test"
};
global.window.setTimeout = setTimeout;

import Webex from "webex";
```

**Error:**  
```
error: uncaughtException: window is not defined
ReferenceError: window is not defined
    at Object.<anonymous> (/app/node_modules/@webex/internal-media-core/dist/cjs/index.js:2065:29024)
    at Module._compile (node:internal/modules/cjs/loader:1368:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1426:10)
    at Module.load (node:internal/modules/cjs/loader:1205:32)
    at Module._load (node:internal/modules/cjs/loader:1021:12)
    at Module.require (node:internal/modules/cjs/loader:1230:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/app/node_modules/@webex/plugin-meetings/dist/meetings/index.js:35:26)
    at Module._compile (node:internal/modules/cjs/loader:1368:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1426:10) {"date":"Tue May 07 2024 21:17:17 GMT+0000 (Coordinated Universal Time)","error":{},"exception":true,"os":{"loadavg":[0.13,0.03,0.01],"uptime":41.03},"process":{"argv":["/usr/bin/node","/app/dist/server.js"],"cwd":"/app","execPath":"/usr/bin/node","gid":0,"memoryUsage":{"arrayBuffers":18265292,"external":20527978,"heapTotal":93507584,"heapUsed":65996192,"rss":174137344},"pid":27,"uid":0,"version":"v21.7.2"},"stack":"ReferenceError: window is not defined\n    at Object.<anonymous> (/app/node_modules/@webex/internal-media-core/dist/cjs/index.js:2065:29024)\n    at Module._compile (node:internal/modules/cjs/loader:1368:14)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1426:10)\n    at Module.load (node:internal/modules/cjs/loader:1205:32)\n    at Module._load (node:internal/modules/cjs/loader:1021:12)\n    at Module.require (node:internal/modules/cjs/loader:1230:19)\n    at require (node:internal/modules/helpers:179:18)\n    at Object.<anonymous> (/app/node_modules/@webex/plugin-meetings/dist/meetings/index.js:35:26)\n    at Module._compile (node:internal/modules/cjs/loader:1368:14)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1426:10)","trace":[{"column":29024,"file":"/app/node_modules/@webex/internal-media-core/dist/cjs/index.js","function":null,"line":2065,"method":null,"native":false},{"column":14,"file":"node:internal/modules/cjs/loader","function":"Module._compile","line":1368,"method":"_compile","native":false},{"column":10,"file":"node:internal/modules/cjs/loader","function":"Module._extensions..js","line":1426,"method":".js","native":false},{"column":32,"file":"node:internal/modules/cjs/loader","function":"Module.load","line":1205,"method":"load","native":false},{"column":12,"file":"node:internal/modules/cjs/loader","function":"Module._load","line":1021,"method":"_load","native":false},{"column":19,"file":"node:internal/modules/cjs/loader","function":"Module.require","line":1230,"method":"require","native":false},{"column":18,"file":"node:internal/modules/helpers","function":"require","line":179,"method":null,"native":false},{"column":26,"file":"/app/node_modules/@webex/plugin-meetings/dist/meetings/index.js","function":null,"line":35,"method":null,"native":false},{"column":14,"file":"node:internal/modules/cjs/loader","function":"Module._compile","line":1368,"method":"_compile","native":false},{"column":10,"file":"node:internal/modules/cjs/loader","function":"Module._extensions..js","line":1426,"method":".js","native":false}]}
```

**Webex:** `v3.0.0`

**Comment by sreenara** [comment]
Marking this as a `feature` and not a `bug`. On closer inspection of the code, what we are observing here is expected behavior. The goal now would be to find out whether we can publish a variant of `webex.min.js` that will NOT require the `window` object. In this variant,
* Not all plugins in the webex-js-sdk will be supported in NodeJS. 
* Functionality such as media handling will not be supported as the `Streams` classes need a browser to acquire the list of devices and use them.

**Comment by enyineer** [comment]
Is this still worked on? No fix since 3 months.
I wouldn't have believed a commercial product to be so badly maintained. Suggesting to use EOL versions of Node just to use an SDK is not something I would expect from Cisco.
Huge Red Flags to avoid this product and rather use competitor products...

**Comment by sreenara** [comment]
> Is this still worked on? No fix since 3 months. I wouldn't have believed a commercial product to be so badly maintained. Suggesting to use EOL versions of Node just to use an SDK is not something I would expect from Cisco. Huge Red Flags to avoid this product and rather use competitor products...

@enyineer yes, we are planning to add support for NodeJS. The team will get to this in a month or so.

>> Just another note that at this time, we haven't tested all the features of the JS SDK with Node 18 and above. Our applications are running Node 16 and consuming the SDK.

> Suggesting to use EOL versions of Node just to use an SDK

The Webex JS SDK can be compiled with Node 20 without any issues.
We've also done some testing on Node 20. Meeting and calling features will work if the SDK is consumed on the client side.

**Comment by johnwfrancis** [comment]
@sreenara until it's fixed I've unpublished our node.js doc since the instructions don't actually work.

**Comment by sreenara** [comment]
An update on this one. Developers can use the `[jsdom-global](https://www.npmjs.com/package/jsdom-global)` package in their applications to avoid hitting the problem while initializing the `webex` object. This works with NodeJS 20.
Example of script:
```
require('jsdom-global')();
const Webex = require('webex');

const webex = (window.webex = Webex.init({
    credentials: {
      access_token: 'token'
    }
  }));

webex.once('ready', () => {
    if (webex.canAuthorize) {
        console.log('webex is authorized');
        webex.rooms.create({
            title: 'Test Space from NodeJS'
        })
        .then(function(room) {
            console.log('room object', room);
            webex.messages.create({
                    text: 'Hello World!',
                    roomId: room.id
                });
        })
        // Make sure to log errors in case something goes wrong.
        .catch(function(reason) {
        console.error(reason);
        process.exit(1);
        });
    }
});
```

**Comment by baranork** [comment]
Are there any news if the Webex SDK 3.0.0 will work on Node 22 when it enters Long Term Support on October?

**Comment by sreenara** [comment]
> Are there any news if the Webex SDK 3.0.0 will work on Node 22 when it enters Long Term Support on October?

@baranork We haven't tested it on Node 22 yet. Are there any differences between Node 20 and 22 which you feel will be a concern?

**Comment by Tiuipuv** [comment]
So far my testing shows that v22 should work for basic tasks, such as room info, post message, etc. However, it is worth noting with the later versions of webex js sdk (`v3.1.X+`), we often get the following errors:
```
failed to execute Logger#log TypeError: Cannot read properties of undefined (reading 'logger')
    at CallDiagnosticMetrics.get (C:\Users\h35529\Downloads\webex-sdk-test\node_modules\@webex\webex-core\dist\lib\stateless-webex-plugin.js:79:25)
    at assignValue (c:\Users\h35529\Downloads\webex-sdk-test\node_modules\lodash\lodash.js:2514:28)
    at c:\Users\h35529\Downloads\webex-sdk-test\node_modules\lodash\lodash.js:2733:9
    at arrayEach (c:\Users\h35529\Downloads\webex-sdk-test\node_modules\lodash\lodash.js:530:11)
    at baseClone (c:\Users\h35529\Downloads\webex-sdk-test\node_modules\lodash\lodash.js:2727:7)
    at c:\Users\h35529\Downloads\webex-sdk-test\node_modules\lodash\lodash.js:2733:34
    at arrayEach (c:\Users\h35529\Downloads\webex-sdk-test\node_modules\lodash\lodash.js:530:11)
    at baseClone (c:\Users\h35529\Downloads\webex-sdk-test\node_modules\lodash\lodash.js:2727:7)
    at c:\Users\h35529\Downloads\webex-sdk-test\node_modules\lodash\lodash.js:2733:34
    at arrayEach (C:\Users\h35529\Downloads\webex-sdk-test\node_modules\lodash\lodash.js:530:11) {stack: 'TypeError: Cannot read properties of undefine…test\\node_modules\\lodash\\lodash.js:530:11)', message: "Cannot read properties of undefined (reading 'logger')"}
```

This is including the workaround of adding `require('jsdom-global')();`.

**Comment by Tiuipuv** [comment]
Just FYI for anyone still battling issues w/NodeJS:

Firstly, I do not recommend the solution of using `require('jsdom-global')();`, as it will pollute over top of and break lots of NodeJS globals, for example, `atob()`, if referenced anywhere in your codebase, will now throw an exception. Instead, stick to the dangerous but more functional setting of global.window, like this:
```js
global.window = {};
global.window.location = {};
global.window.navigator = {
  userAgent: 'test'
};
global.window.setTimeout = setTimeout;
```

Additionally, the logging exceptions the sdk throws was implemented by commit [fd73d67](https://github.com/webex/webex-js-sdk/commit/fd73d6751ade556ad7369e54c8d8f3ba5a59fafb), released in [v3.1.0-next.11](https://github.com/webex/webex-js-sdk/releases/tag/v3.1.0-next.11), so if you want to decrease exceptions produced from the library, revert to `v3.10-next.10` or older.

Lastly, for NodeJS `v22.X` or newer, you will see the following deprecation warning:
```
(node:657326) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
```

This is produced by `@webex/http-core` having a dependency on the deprecated [request](https://www.npmjs.com/package/request) module. This is fixed on [@cypress/request](https://www.npmjs.com/package/@cypress/request)'s fork of request, but would need to be implemented in @webex/http-core's [package.json](https://github.com/webex/webex-js-sdk/blob/next/packages/%40webex/http-core/package.json).

**Comment by sreenara** [comment]
Here's another workaround on this issue which was used. Simply create a wrapper around the initialization of `webex` by importing all the plugins you need separately _except @webex/plugin-meetings_.
With this, you can get around the `window` error in NodeJS.

```
import '@webex/plugin-authorization';
import '@webex/internal-plugin-calendar';
import '@webex/internal-plugin-device';
import '@webex/internal-plugin-presence';
import '@webex/internal-plugin-support';
import '@webex/internal-plugin-llm';
import '@webex/plugin-attachment-actions';
import '@webex/plugin-device-manager';
import '@webex/plugin-logger';
import '@webex/plugin-messages';
import '@webex/plugin-memberships';
import '@webex/plugin-people';
import '@webex/plugin-rooms';
import '@webex/plugin-teams';
import '@webex/plugin-team-memberships';
import '@webex/plugin-webhooks';
import WebexCore, { MemoryStoreAdapter } from '@webex/webex-core';

const config = {
  hydra: process.env.HYDRA_SERVICE_URL || 'https://api.ciscospark.com/v1',
  hydraServiceUrl:
    process.env.HYDRA_SERVICE_URL || 'https://api.ciscospark.com/v1',
  credentials: {
    clientType: 'confidential',
  },
  device: {
    validateDomains: true,
    ephemeral: true,
  },
  storage: {
    boundedAdapter: MemoryStoreAdapter,
    unboundedAdapter: MemoryStoreAdapter,
  },
};

// documentation.js puts hashes in relative urls, so need to specify full urls
// here
/**
 * See {@link https://webex.github.io/webex-js-sdk/example/browsers|Browser Guide} and
 * {@link https://webex.github.io/webex-js-sdk/example/servers|Server Guide}
 * @see {@link /example/browsers|Browser Guide}
 * @see {@link /example/servers|Server Guide}
 */
const Webex = WebexCore.extend({
  webex: true,
  version: '0.0.0-custom',
});

Webex.init = function init(attrs: any = {}) {
  attrs.config = {
    sdkType: 'webex',
    ...config,
    ...attrs.config,
  };

  const webex = new Webex(attrs);

  webex.logger = logger;
  return webex;
}; 
```

**Comment by sreenara** [comment]
`webex-node` package is now available in NPM https://www.npmjs.com/package/webex-node
